added functions

diff --git a/bn b/bn
--- a/bn
+++ b/bn
@@ -1,21 +1,93 @@
 #!/bin/bash
 
+#########################################################################
+#Name: Rushil Karani
+#MacID: karanir
+#The Bash Assignment
+#Looks through a database of US baby names and prints the rank of a name.
+#########################################################################
+
 usage(){
 	echo "bn <year> <assigned gender: f|F|m|M|b|B>">&2
 }
 
+help(){
+    echo "Baby Names Utility v1.0.0"
+    echo "Overview: Allows users to search for US baby name rankings"
+    echo "for a given year and gender. Uses data from the U.S. baby names data."
+    echo "Usage: bn <year> <assigned gender: f|F|m|M|b|B>"
+    echo "  <year>                The year (four digits) for which to retrieve name rankings"
+    echo "  <assigned gender>     f|F|m|M|b|B (f for female, m for male, b for both)"
+    exit 0
+}
+
+rank(){
+    local name=$1
+    local gender=$2
+    local file=$3
+    local year=$4
+
+    if [[ $gender =~ ^[fF]$ ]]
+    then
+        female_rank=$(grep -n -i "^$name,F," "$file" | grep -o '^[0-9]*')
+
+        if [ -n "$female_rank" ]
+        then
+            echo "$year: $name ranked $female_rank out of $female_total female names."
+        else
+            echo "$year: $name not found among female names."
+        fi
+    fi
+
+    if [[ $gender =~ ^[mM]$ ]]
+    then
+        male_rank=$(grep -n -i "^$name,M," "$file" | grep -o '^[0-9]*')
+
+        if [ -n "$male_rank" ]
+        then
+            echo "$year: $name ranked $male_rank out of $male_total male names."
+        else
+            echo "$year: $name not found among male names."
+        fi
+    fi
+
+    if [[ $gender =~ ^[bB]$ ]]
+    then
+        female_rank=$(grep -n -i "^$name,F," "$file" | grep -o '^[0-9]*')
+        male_rank=$(grep -n -i "^$name,M," "$file" | grep -o '^[0-9]*')
+
+        if [ -n "$female_rank" ]
+        then
+            echo "$year: $name ranked $female_rank out of $female_total female names."
+        else
+            echo "$year: $name not found among female names."
+        fi
+
+        if [ -n "$male_rank" ]
+        then
+            echo "$year: $name ranked $male_rank out of $male_total male names."
+        else
+            echo "$year: $name not found among male names."
+        fi
+    fi
+}
+
 if [ "$#" != 2 ]
 then
-	
 	usage
 	exit 1
 fi
 
-local year="$1"
-local file="us_baby_names/yob$year.txt"
-local gender="$2"
+if [[ $1 == "--help" ]]
+then
+	help
+fi
 
-if ! [[ $year =~ "^[0-9]{4}$" ]]
+year="$1"
+file="us_baby_names/yob$year.txt"
+gender="$2"
+
+if ! [[ $year =~ ^[0-9]{4}$ ]]
 then
 	echo "Badly formatted year: $year">&2
 	usage
@@ -28,73 +100,25 @@ then
     exit 4
 fi
 
-if ! [[ $gender =~ "^[fmbFMB]$" ]]
+if ! [[ $gender =~ ^[fmbFMB]$ ]]
 then
-    echo "Badly formatted assigned gender: $year">&2
+    echo "Badly formatted assigned gender: $gender">&2
     usage
     exit 2
 fi
 
-local female_total=$(grep -c ",F," "$file")
-local male_total=$(grep -c ",M," "$file")
+female_total=$(grep -c ",F," "$file")
+male_total=$(grep -c ",M," "$file")
 
 while read name
 do
-	if ! [[ $name =~ "[A-Za-z]+" ]]
+	if ! [[ $name =~ ^[A-Za-z]+$ ]]
 	then
-		echo "Badly formated name: $name">&2
+		echo "Badly formatted name: $name">&2
 		exit 3
 	fi
 
-	if [[ $gender =~ "^[fF]$" ]]
-	then
-		female_rank=$(grep -n -i "^$name,F," "$file" | cut -d':' -f1)
-		rank=$(echo "$female_result" | cut -d':' -f1)
+	rank "$name" "$gender" "$file" "$year"
 
-		if [ -n $female_rank ]
-		then
-			echo "$year: $name ranked $female_rank out of $female_total female names."
-		else
-			echo "$year: $name not found among female names."
-		fi
-	fi
-
-	if [[ $gender =~ "^[mM]$" ]]
-    then
-        male_rank=$(grep -n -i "^$name,M," "$file" | cut -d':' -f1)
-
-        if [ -n $male_rank ]
-        then
-            echo "$year: $name ranked $male_rank out of $male_total male names."
-        else
-            echo "$year: $name not found among male names."
-    	fi
-	fi
-
-	if [[ $gender =~ "^[bB]$" ]]
-    then
-        female_rank=$(grep -n -i "^$name,F," "$file" | cut -d':' -f1)
-		male_rank=$(grep -n -i "^$name,M," "$file" | cut -d':' -f1)
-
-        if [ -n $female_rank ]
-        then
-            echo "$year: $name ranked $female_rank out of $female_total female names."
-        else
-            echo "$year: $name not found among female names."
-    	fi
-
-		if [ -n $male_rank ]
-        then
-            echo "$year: $name ranked $male_rank out of $male_total male names."
-        else
-            echo "$year: $name not found among male names."
-		fi
-	fi
 done
-
-
-
-
-
-
 
